name: 'customer_orders_analytics'
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['data']
macro-paths: ['macros']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_modules'

seeds:
  customer_orders_analytics:
    +schema: raw_data

models:
  customer_orders_analytics:
    stg:
      +schema: stg
      +materialized: view
    int:
      +schema: int
    marts:
      +schema: marts
